name: Python Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Python Unittests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run program
        run: python3 main.py "2+2" "3^3"

      - name: Run tests
        run: python3 -m unittest -v